# Site settings
title: PMBIO
slogan: Precision Medicine Workshop
email:
author:
description:
url:

# Build settings
permalink: :title/
sass:
  sass_dir: _sass
include: ['_sass']

# favicons
favicon-32x32: favicon_32x32.png

# markdown
markdown: kramdown
